# Generated by Django 6.0.3 on 2026-03-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_id',
        ),
    ]
