# Generated by Django 6.0.3 on 2026-03-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_customuser_is_authorized_customuser_login_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='NPY61H3PBMhYT8A6wiSQTfbTcVOumJlx', editable=False, max_length=32, unique=True),
        ),
    ]
