# Generated by Django 6.0.3 on 2026-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ihQGpmxxHHodwpMDcn6nO7B1J79c84wH', editable=False, max_length=32, unique=True),
        ),
    ]
