# Generated by Django 6.0.3 on 2026-03-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='pEtPjHkVCmbvuchTpLBVZg0obo285G6S', editable=False, max_length=32, unique=True),
        ),
    ]
