# Generated by Django 6.0.3 on 2026-03-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='HchM1RVNI6HXtp5T9RIMrT3O5dqFICTW', editable=False, max_length=32, unique=True),
        ),
    ]
