# Generated by Django 6.0.3 on 2026-03-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gG7ysMrIGe8xBdX5ANhvZyxztyjDIPXz', editable=False, max_length=32, unique=True),
        ),
    ]
