# Generated by Django 6.0.3 on 2026-03-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0010_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='amEeP9pdFS1X37Bot6AaZJ2QZJcjQSO2', editable=False, max_length=32, unique=True),
        ),
    ]
