# Generated by Django 6.0.3 on 2026-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0012_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='GEStf9ucEuxhkhXuRW61dF8Vg9bvuvKP', editable=False, max_length=32, unique=True),
        ),
    ]
