# Generated by Django 6.0.3 on 2026-03-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0013_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='jFm1QZ9dhKb9vUAQIkVpVfuT2hRD04US', editable=False, max_length=32, unique=True),
        ),
    ]
