# Generated by Django 6.0.3 on 2026-03-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0015_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='u6ox0iPuLeWpF2hdFsFneblxcW7owihk', editable=False, max_length=32, unique=True),
        ),
    ]
