# Generated by Django 6.0.3 on 2026-03-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0016_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='cESlLea3xBmN1rYEEqwdI7vkPx3uFGUr', editable=False, max_length=32, unique=True),
        ),
    ]
