# Generated by Django 6.0.3 on 2026-03-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0017_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Mg0D4ikZ5YY7tUd6GrIC9ceJuKBaB2co', editable=False, max_length=32, unique=True),
        ),
    ]
