# Generated by Django 6.0.3 on 2026-03-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0018_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='nXiUPr1WVtiMI0R48jFqe4xi2yahVN6L', editable=False, max_length=32, unique=True),
        ),
    ]
