# Generated by Django 6.0.3 on 2026-03-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0020_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='1Fre4OvNn8Me5MRfT9WgKC7XL3MnfCZT', editable=False, max_length=32, unique=True),
        ),
    ]
