# Generated by Django 6.0.3 on 2026-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0022_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='qOkp3eDwUnRfDuRl0TSgX4tcgofRHWHg', editable=False, max_length=32, unique=True),
        ),
    ]
