# Generated by Django 6.0.3 on 2026-03-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0023_alter_passwordresetrequest_token'),
        ('home_auth', '0023_customuser_profile_pic_and_more'),
    ]

    operations = [
    ]
