# Generated by Django 6.0.3 on 2026-03-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0024_merge_20260327_1837'),
        ('home_auth', '0024_merge_20260327_1850'),
    ]

    operations = [
    ]
