# Generated by Django 6.0.3 on 2026-03-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0025_merge_20260327_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='6HOtKb5nDL74EaTwcri3LLBca9OaZ4hp', editable=False, max_length=32, unique=True),
        ),
    ]
