# Generated by Django 6.0.3 on 2026-03-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0027_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='elUNyqQLTP5qbL56GHjR1p9XVDI2L0EO', editable=False, max_length=32, unique=True),
        ),
    ]
