# Generated by Django 6.0.3 on 2026-03-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0029_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='M4CCNwalVf8PHsth38DMRrOosHwBcfQI', editable=False, max_length=32, unique=True),
        ),
    ]
